---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: pos
spec:
  encryptedData:
    .dockerconfigjson: AgBVI3NH42+T+BME7+/i1E/P5RWN4Z5fnuIcJ5YOD+ZC/sawIbQ+dd4JWhWLPGjhXv+Fjz7RUr34wMH8XxiJMKrd1az6Rv/Z1rKqC43IgLAFNxSy1OhyhSNmdNCanQvqCyMKcEADJwNfuMZzhHs5bYVYeB4Lxk+duaVB8uzxDs1PfpisqAEwZdGJiwF6Zv5HCv7B+kty5glXRMcIGWd29bBxQysFfFKTzGTtXGMmvml95AySdmiRZ9UzTF1A6I65AzPO0U5WeG6Pihi7TsuXaLtF9gWny2wFZyokxK0qvc1oOaYJsbklBdicazyQVWwzBxgfiuC8xb4W8Emz5kovkoIXqPCPMiyU6+mZ/q5qr43b2EVGGXo0foCYQErjeACuHinzmuX0bx4ASUeB/e5FTBHk9GyeCzOgPxpoRfKkxsm3oKSpZU9xP0QH/hFbCuqvebscFZoMpYLJBSOxM+4irYDJnhCnCsyu1HL6/Eh/AKNXtE/2+pO9ixGjmNG2j6T1xVFR//UEi21zE3ZbD6rki5VhS3pVBxpR9VALDKsqRPiN5PrnX2oe/KG2GIe8ZvGsEQUg0wI2Ay1uJQs1XuHWhStZT5qTwcvRm3RlQuIN9nVD4jVs5EyEN2RKLtWTn8PeA6KoH9iK2NV+GJZ2fEiErqDrOMhhA15s3LBWFijuelvtcJSfpb3nY9H9qHUWEw+RAYovIWHaRBzuCx0uJf1/arEm4qCvWKauoeaAnhsNfVnsR+AC2Nods80DItFckitiK5LpM/G9yE2CSk9bGmSw1AD+/PJtW96D4yJnEgWP8+A/vEsdegh0rfVDBqE9NNz4yvljTyCMxRYadRPVhBCNmpUK0N8QHHez+yi6U0INIZLtLb6eQKAui5oa0CEwYyInA8WQj2xM5+kVelS309lU4x07YaCp7H/csZp9ClxZV522Gp0=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: pos
    type: kubernetes.io/dockerconfigjson
