apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: influxdb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  admin-password: moody422!
  admin-token: 2f07d03b-6b72-477d-9cdd-417879fad3f2
