apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/home-assistant/helm-charts
    chart: home-assistant
    targetRevision: 0.2.63
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - host: ha.discovery.local
              paths:
                - path: /
                  pathType: Prefix
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
