apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - grafana.discovery.local
