apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    helm:
      values: |
        persistence:
          enabled: true
          storageClassName: local-path
          size: 2Gi    # bigger PVC in prod
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
