apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    helm:
      values: |
        persistence:
          enabled: true
          storageClassName: local-path
          accessModes: [ "ReadWriteOnce" ]
          size: 5Gi
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hosts:
            - grafana.discovery.local
        admin:
          existingSecret: grafana-admin
