apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
        - apps/grafana/base/values-common.yaml
        - apps/grafana/overlays/prod/values-prod.yaml
