apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
        - values-common.yaml
        - overlays/prod/values-prod.yaml
