apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: pos-rabbit
  namespace: rabbitmq
spec:
  replicas: 3
  persistence:
    storage: 1Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = autoheal
      queue_master_locator = min-masters
      queue_type = quorum
