apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: "*" # always pull latest
    helm:
      values: |
        auth:
          username: admin
          existingPasswordSecret: rabbitmq-auth
          erlangCookie: "supersecretcookie"

        persistence:
          enabled: true
          size: 1Gi

        clustering:
          enabled: true
          addressType: hostname

        replicaCount: 3

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        # Use safer readiness/liveness probes
        livenessProbe:
          exec:
            command:
              - rabbitmq-diagnostics
              - -q
              - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6

        readinessProbe:
          exec:
            command:
              - rabbitmq-diagnostics
              - -q
              - check_running
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6

        extraConfiguration: |-
          cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
          cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
          cluster_formation.node_cleanup.only_log_warning = true
          cluster_partition_handling = autoheal
          queue_master_locator = min-masters
          queue_type = quorum
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
