apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.1.2 # check latest before applying
    helm:
      values: |
        auth:
          username: admin
          existingPasswordSecret: rabbitmq-auth
          existingPasswordKey: password
        persistence:
          enabled: true
          size: 10Gi
        clustering:
          enabled: true
          addressType: hostname
        replicaCount: 3
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
