apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signalk
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: signalk.discovery.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signalk
                port:
                  number: 3000
