apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signalk-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   # adjust if you need more
