apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  namespace: pos
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: pos
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
