apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  namespace: pos
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pos
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 300Mb
