apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-config
  namespace: pos
data:
  RUST_LOG: "info"
  # service endpoints (DNS works because they are in cluster)
  RABBITMQ_URL: "amqp://user:password@rabbitmq.rabbitmq:5672/%2f"
  TYPESENSE_URL: "http://typesense.typesense:8108"
  POSTGRES_HOST: "postgresql.postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "posdb"
