apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: influxdb
spec:
  project: platform
  source:
    repoURL: https://helm.influxdata.com/
    chart: influxdb2
    targetRevision: 2.1.2 # check latest version
    helm:
      values: |
        persistence:
          enabled: true
          size: 5Gi
        adminUser:
          organization: influxdb
          bucket: "telemetry"
          user: "admin"
          password: "moody422!"
          token: "be6171ab-7b79-42b7-98f2-83e1adf86890"
        ingress:
          enabled: true
          ingressClassName: traefik
          hostname: influx.discovery.local
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
