apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    chart: home-assistant
    targetRevision: 0.3.19 # check latest
    helm:
      values: |
        persistence:
          enabled: true
          size: 10Gi
          storageClass: local-path

        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: ha.discovery.local
              paths:
                - path: /
                  pathType: Prefix

        service:
          type: ClusterIP

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi

        configuration:
          enabled: true
          forceInit: false
          templateConfig: |-
            default_config:

            http:
              use_x_forwarded_for: true
              trusted_proxies:
                - 0.0.0.0/0
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
