apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
        - manifests/ha/base/values.yaml
        - manifests/ha/overlays/prod/values-prod.yaml
