# apps/grafana/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: discovery
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.6.0
    helm:
      values: |
        adminUser: admin
        adminPassword: "moody422!"
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated: { prune: true, selfHeal: true }
