apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signalk-config
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # default size for dev/test
