apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influx
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://helm.influxdata.com/
    chart: influxdb2
    targetRevision: 2.1.0
    helm:
      values: |
        ingress:
          enabled: true
          hostname: influx.discovery.local
        persistence:
          enabled: true
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
